BUG: Avoid mismatched size on Windows by specifying binary text format
The error message was:

Error: Could not read output log file 'C:/Misc/ITK-IOOpenSlide-vs22/Testing/Temporary/IOOpenSlide/MetaDataTest.txt'.

and it was caused by failure of fileStream.read() on line 64.